### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by oubiwann** [clojusc/shankha#1]
This will involve basically copying what has been done in this file:
- https://raw.githubusercontent.com/clojusc/reggae/master/README.md

Tasks:
- [x] In the reggae project's README `#` heading (first line), copy everything after the heading (all the short links) and paste them into the shankha project's README
- [x] At the bottom of the reggae project's README, everything from `<!-- Named page links below: /-->` until the end of the file (including the comment) and paste it into the shankha project's README
- [x] Update all the copied links to use "shankha" instead of "reggae"
- [x] Double-check the logo link -- a logo link is defined at the top of the README; be sure that this gets moved to the bottom where the rest of the new (badge) links are getting added and that it only appears once

**Comment by miyurusankalpa** [comment]
what badges do you need?

**Comment by tensorflow1** [comment]
I am up for this.Kindly assign me this issue.

**Comment by oubiwann** [comment]
I'll update the description with what tasks need to be performed and related details.

**Comment by oubiwann** [comment]
@miyurusankalpa was here first, so if they still want this, they can do it. If we don't hear back, then @tensorflow1, you can have it.

**Comment by miyurusankalpa** [comment]
I am on it

**Comment by oubiwann** [comment]
@miyurusankalpa: Great, thanks!

**Comment by oubiwann** [comment]
@miyurusankalpa: Note, I've updated the README with the logo links, so I'm going to change the last task in the description of this ticket ... it will basically be a warning of avoiding the logo image being defined twice.

**Comment by miyurusankalpa** [comment]
does that look good?

**Comment by oubiwann** [comment]
Yup, looks good! Preparing to merge...

**Comment by oubiwann** [comment]
Done.

**Comment by oubiwann** [comment]
Thanks, @miyurusankalpa!
