### ISSUE TITLE
Add Missing Sections and ToC to README

### ISSUE THREAD

**Issue by oubiwann** [clojusc/shankha#2]
Here is an example of the ToC format I use on projects:
- https://github.com/USGS-EROS/lcmap-see

Here's another one, which you can almost copy-and-paste from:
- https://github.com/clojusc/meson/blob/master/README.md

Tasks:
- [x] Ensure that the LICENSE has been added (see ticket #4)
- [x] Add an "About" section (with content TBD)
- [x] Add a "Dependencies" section (with content TBD)
- [x] Add a "Documentation" section with a link to (yet-to-be-created) docs site, a la https://github.com/clojusc/meson/blob/master/README.md (be sure that the URL is actually for this project, though: http://clojusc.github.io/shankha/
- [x] Add a "Usage" section (blank, like in the README linked in the previous task)
- [x] Make sure that every section heading is of heading type `##`
- [x] Make sure that every section heading has this appended to it: `[&#x219F;](#contents)`
- [x] After the project description at the top of the README, add  `#### Contents`
- [x] Under the "Contents" heading, provide a list of sections, in the same way that is done in https://raw.githubusercontent.com/clojusc/meson/master/README.md

**Comment by tensorflow1** [comment]
What do you need in ToC??
I am up for this

**Comment by oubiwann** [comment]
I'll update the description with info/tasks.

**Comment by oubiwann** [comment]
@tensorflow1 This one's ready for you now.

**Comment by oubiwann** [comment]
I need this now, so I'm going to take it.

**Comment by oubiwann** [comment]
Done.
