### ISSUE TITLE
Ditch JRuby POSIX dep

### ISSUE THREAD

**Issue by bjorstrom** [clojusc/shankha#20]
Use  beckon instead:
- https://github.com/hyPiRion/beckon

Or even just `clojure.repl`:
 *`clojure.repl/set-break-handler!`

Anything but JRuby ...

**Comment by bjorstrom** [comment]
Huh. Seems like the only thing that the JRuby POSIX lib is used for is cd? C'mon, guys ... this isn't node!

**Comment by oubiwann** [comment]
To be fair, the JRuby lib looked like it was trying to solve the harder problem of change dir persistence and file handling, etc. Kind of a sticky issue in Java. But I don't think this project needs anything serious for that -- you're solution is great :-)

**Comment by bjorstrom** [comment]
True.

Thanks for the merge, btw.

I don't think, however, that my fix is going to work ... I'm going to re-open, and keep working on this ...

**Comment by bjorstrom** [comment]
Okay, this has been merged with a proper fix -- thanks for the help, @oubiwann!
