### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by oubiwann** [clojusc/shankha#3]
Once ticket #1 is done, there will be a link to the service that lists out of date deps for Clojure projects.

If you don't want to wait, simply search Clojars and/or github for all the deps in this project and ensure that the versions listed in `project.clj` are at the latest.

Clojure may be updated to 1.8, but not 1.9 (alpha).

**Comment by ashutosh1206** [comment]
Can you please tell what dependencies you wish to have?

**Comment by oubiwann** [comment]
I'll update the description ...

**Comment by oubiwann** [comment]
Fixed.
