### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by oubiwann** [clojusc/shankha#4]
Tasks:
- [x] Add a LICENSE file for Apache 2.0 License (e.g., copy from https://github.com/clojusc/meson project)
- [x] Update the license section of the `project.clj` file (look at https://github.com/clojusc/meson/blob/master/project.clj for an example of this)
- [x] Add a "License" section to the README (see https://github.com/clojusc/meson/blob/master/README.md)
- [x] Ensure that the copyright in the LICENSE file uses the date range 2013-2016
- [x] Ensure that the copyright in the "License" section of the README uses the date range 2013-2016

**Comment by aedorado** [comment]
Hello! I am on it.

**Comment by oubiwann** [comment]
Great!

**Comment by aedorado** [comment]
Should the Eclipse license be removed in project.clj file?

**Comment by oubiwann** [comment]
Yes please!

**Comment by oubiwann** [comment]
Thanks again!
